# -*- coding: utf-8 -*-
"""Data Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ee2eJ9xyjn7yUnEejcgBeZIinJNPnCFe
"""

# Importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Importing the dataset
dataset = pd.read_csv("covid_data.csv")

# Display basic information about the dataset
print(dataset.info())

# Descriptive statistics
print(dataset.describe())

# Correlation matrix
correlation_matrix = dataset.corr()
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix')
plt.show()

# Pairplot to visualize relationships between variables
sns.pairplot(dataset, diag_kind='kde')
plt.suptitle('Pairplot for Numeric Variables', y=1.02)
plt.show()

# Boxplot to identify outliers
plt.figure(figsize=(12, 6))
sns.boxplot(x='location', y='new_cases', data=dataset)
plt.xticks(rotation=90)
plt.title('Boxplot of New Cases by Location')
plt.show()

# Distribution of new cases
plt.figure(figsize=(10, 6))
sns.histplot(dataset['new_cases'], bins=30, kde=True)
plt.title('Distribution of New Cases')
plt.xlabel('New Cases')
plt.ylabel('Frequency')
plt.show()